### ISSUE TITLE
API failed

### ISSUE THREAD

**Issue by n3rotech** [hugofirth/laravel-mailchimp#12]
Anyone helps me.im get this error while use this bundle:
{"error":{"type":"Mailchimp_HttpError","message":"API call to lists\/subscribe failed: SSL certificate problem: unable to get local issuer certificate","file":"C:\Users\mpermadi\Documents\mobile_thelife\vendor\mailchimp\mailchimp\src\Mailchimp.php","line":314}}

thank you

**Comment by ghost** [comment]
@kapik Thanks!

**Comment by princelionelnzi** [comment]
@kapik Thanks!
