### ISSUE TITLE
Class 'HugoFirth\Mailchimp\Facades\MailchimpWrapper' not found

### ISSUE THREAD

**Issue by maksl** [hugofirth/laravel-mailchimp#35]
Your Facade uses `namespace HugoFirth\Mailchimp`, 
when all other files uses `namespace Hugofirth\Mailchimp`

IDE autocompletes MailchimpWrapper' wrong namespace, and it causes an exception 
`'ErrorException' with message 'Class 'HugoFirth\Mailchimp\Facades\MailchimpWrapper' not found'`.

P.S. It is not an critical issue and is solved easily with manual namespace declaration :)

**Comment by hadifarnoud** [comment]
I have the same issue. how can I fix it?

**Comment by vpakg** [comment]
Hey @hadifarnoud , as @maksl explained, you just need to correct the casing of the namespace.Just change `HugoFirth\Mailchimp` to `Hugofirth\Mailchimp`.

**Comment by hadifarnoud** [comment]
@vpakg is the package going to update with this fix?

**Comment by vpakg** [comment]
Hey @hadifarnoud , I'm not a contributer to the package. We can do a pull request, but there is no garantee that the maintainers will merge.

**Comment by hugofirth** [comment]
I have updated master to include this simple fix. I'll tag a path release later today once I make sure there aren't other changes on master which shouldn't be tagged as a patch.
